### ISSUE TITLE
DB enrichment of Documents

### ISSUE THREAD

**Issue by angelo337** [Norconex/collector-filesystem#10]
hi there I manage to work with the file collector , and now I want to include more data that is store on a DB Oracle, Is it possible to enrich my files search with DB information ? if so could you please point me out some resource or privedeme some information regarding how to make it work?
thanks

**Comment by essiembre** [comment]
There are different ways to do this, but it likely requires sharing more information.  The Filesystem Collector can be extended in many ways.  For instance, you can provide your own implementation of some of the existing classes (like [IDocumentTagger](https://www.norconex.com/collectors/importer/latest/apidocs/com/norconex/importer/handler/tagger/IDocumentTagger.html)) to make DB calls to grab more info and store it as additional metadata.  This is not something offered out-of-the-box but if you know your Java it should be relatively simple for you to do.  Else, you can always contact us to have that custom solution created for you.

**Comment by angelo337** [comment]
thank you very much for your answer, I am going to take and look and in case get back to you 
Regards
