### ISSUE TITLE
JCIFS ACL integration and extraction feature request

### ISSUE THREAD

**Issue by angelo337** [Norconex/collector-filesystem#12]
hi there 
I am working with a file server folders and manage to make it work, and the user is asking me about Security on the search results, I manage to find a resource (ManifoldCF) to work with it, however that is not as fast as your collector, in that regard I was wondering if it's possible to integrate JCIFS in your collector? in order to pull all ACL information, as I found in [here ](https://github.com/kohsuke/jcifs/blob/master/examples/AclCrawler.java) also here are several [examples](https://github.com/kohsuke/jcifs/tree/master/examples)
thanks a lot for your time
Best Regards
angelo

**Comment by essiembre** [comment]
Thanks for using our collector. 

Integrating JCIFS is already possible, see here: #3.

For ACL support, this is already a feature request.

One of the issue that prevents looking into this sooner than later, is the lack of environment to try it out.  If you happen to have one you can share, it may speed up the process.   Of course we are always open for contributions.  ;-)

As this is a duplicate, please report feedback on the matter here: #3.
