### ISSUE TITLE
Filesystem collector gets stuck

### ISSUE THREAD

**Issue by jetnet** [Norconex/collector-filesystem#13]
Hi Norconex team,

I found the following issue: if a document cannot be parsed (e.g. a Tika parser exception), then the collector gets stuck when all files are crawled/checked and never enters the commit stage.

[bad file example](https://www.dropbox.com/s/4brn2vazmqrf61s/Microsoft_Visio_Drawing11-test.vsdx?dl=1)
Version: norconex-collector-filesystem-2.7.0-20170220.195133-8.zip
Could you please take a look?
Thanks a lot!

**Comment by essiembre** [comment]
I was able to reproduce with the file you provided.  Will investigate.

**Comment by essiembre** [comment]
I fixed that type of exception causing the collector to get stuck.  In addition, I have added a missing library that now enables clean parsing of that Visio file.  Try the [latest snapshot](https://www.norconex.com/collectors/collector-filesystem/download) and please confirm.

**Comment by jetnet** [comment]
It works!
The greatest support in the world! :)
