### ISSUE TITLE
anyone have experience with box.com?

### ISSUE THREAD

**Issue by jacksonp2008** [Norconex/collector-filesystem#18]
I tried crawling box.com by using a webdav mount on a linux machine.  This did not return a usable link back to the original file.  Box uses "shared links" which provide direct access to the file.  Note there is an API to generate a link based on the file ID.  (assuming you have the file ID)

I'm wondering if I should be using a different approach, perhaps crawl the web interface to box.com, but it is currently authenticated via OKTA as well.

Any advice appreciated

thanks!

**Comment by essiembre** [comment]
Interesting... I haven't used Box in a while, but I realize it does not offer a way to access files by their actual path.  Do you get the id by any chance as part of the metadata obtained when crawling?

If now, as opposed to crawl the files using a mount point, which makes it appear like a local filesystem, have you tried remote crawling by using webdav URI scheme: 

webdav://[ username[: password]@] hostname[: port][ absolute-path]

Maybe this will offer more metadata information, including the ID.  Worth a try.
