### ISSUE TITLE
Timestamp vs Checksum?

### ISSUE THREAD

**Issue by jmrichardson** [Norconex/collector-filesystem#19]
Hi,

I was hoping there would be an option to speed up re-indexing file system data.  Currently, I believe that each file needs to be read and checksummed to be compared to the original scan.  Unfortunately, this takes a considerable amount of time considering that many of my files are very large.  I was wondering if there is an option to just check file medatdata such as timestamp delta which would significantly improve performance.

Thanks, John

**Comment by essiembre** [comment]
The default behavior should be as you expect.  Unless you changed the default or disabled it, the [FileMetadataChecksummer](https://www.norconex.com/collectors/collector-filesystem/latest/apidocs/com/norconex/collector/fs/checksum/impl/FileMetadataChecksummer.html) is in effect and uses a combination of document lastModified and size to perform a checksum (so does not parse the document if these two things did not change.

Is it possible your date always changes?

If you want more control on what fields are used to create a checksum out of metadata, you can use: [GenericMetadataChecksummer](https://www.norconex.com/collectors/collector-core/latest/apidocs/com/norconex/collector/core/checksum/impl/GenericMetadataChecksummer.html) instead.

**Comment by jmrichardson** [comment]
Thanks, I will do some testing and report back.  Thanks for the help

**Comment by jmrichardson** [comment]
Hi, I am re-indexing the files and I think I may be confused as to the difference between "start" and "resume" when executing the collector-fs.sh script.  

Does "start" start over and re-index everything regardless of previous runs?  Or does it still check the checksums and just index those that have changed?

"resume" I believe does check the checksums of the metadata but not sure if it starts over from scratch checking all files or if it picks off from a "ctrl-c" of previous run or the end of a previous run.  

I will do so more testing ... Thanks.

**Comment by jmrichardson** [comment]
It looks like start and resume will do a comparison of checksum on subsequent runs as well as detect previous runs if terminated before finishing.  Is this accurate?  I am not sure I understand how they differ.  Thanks

**Comment by jmrichardson** [comment]
I am closing this because the default behavior is as you described.  Thank you

**Comment by essiembre** [comment]
The incremental run will always take place unless you remove the "crawl store".  The "resume" option is only useful when the collector did not complete its run (either it was stopped by you, or crashed for some reason).  Upon such failure, you can resume the failed crawl session, or start a new one (still checking for modified documents in both cases).

A concrete example may be that you need to reboot the server where the collector is running.  You can stop the collector, reboot, then resume where it stopped.
