### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by jmrichardson** [Norconex/collector-filesystem#20]
Hi,

Is it possible to re-run the crawler to only process the failed files only?  That is, re-run the crawler to only index the failed files from previous run?

**Comment by essiembre** [comment]
I am not sure this can be done out of the box right now.   When you recrawl the unmodified ones should not be processed again (and won't be sent to your Committer).  So you should get only new/modified/deleted as well as failed ones that are no longer failing.

If you really want to do this, you can implement your own (ICrawlerEventListener)[https://www.norconex.com/collectors/collector-core/latest/apidocs/com/norconex/collector/core/crawler/event/ICrawlerEventListener.html] that stores paths to failing documents in a flat file that you can then use as a seed file for a new run.

**Comment by jmrichardson** [comment]
Thank you, I will look into this as an option
