### ISSUE TITLE
Custom meta data fetcher fetching metadata from external properties file

### ISSUE THREAD

**Issue by jayjamba** [Norconex/collector-filesystem#21]
[MyMetadataFetcher.zip](https://github.com/Norconex/collector-filesystem/files/1655329/MyMetadataFetcher.zip)
Hi,
Is there a way to fetch meta data from external properties file. We have integrated norconex in spring boot application, I declared my own custom class as Spring component , it extends "GenericFileMetadataFetcher"  class. Not sure how can I fetch meta data from external property file ?

Below is my sample metadata fetcher tag that I declared in sample config xml:
<metadataFetcher class="com.sample.metadata.MyMetadataFetcher" />

If I hardcode the metadata in the above class its getting added in xml files which are generated, but I dont want to hardcode these metadata properties, instead I want it to add these metadata from the property file. I have attached 'MyMetadataFetcher' class

**Comment by jayjamba** [comment]
@SpringBootApplication
public class FilesystemconnnectorApplication implements CommandLineRunner {

	// @Autowired
	// private MyMetadataFetcher customFetcher;

	@Autowired
	private ApplicationProperties applicationProperties;

	public static void main(String[] args) {
		SpringApplication.run(FilesystemconnnectorApplication.class, args);
	}

	@Override
	public void run(String... args) throws Exception {
		final File configFile = new File(getClass().getClassLoader().getResource("sample-config.xml").getFile());
		final File variableFile = new File(getClass().getClassLoader().getResource("sample-config.variables").getFile());

		final CollectorConfigLoader collectorConfigLoader = new CollectorConfigLoader(FilesystemCollectorConfig.class);
		final FilesystemCollectorConfig fileCollectorConfig = (FilesystemCollectorConfig) collectorConfigLoader
				.loadCollectorConfig(configFile, variableFile);
		final FilesystemCollector collector = new FilesystemCollector(fileCollectorConfig);

		collector.start(true);
	}
}

This is the way my spring boot app starts.

**Comment by jayjamba** [comment]
I achieved this using ConstantTagger in preParseHandlers. But I was just wondering How can I read the external properties from my own MyMetadataFetcher ?

Below is my constant tagger that worked :

**Comment by essiembre** [comment]
To be clear: you want to read a .properties file and add its content to a document metadata via your code?

Have you tried creating your ApplicationProperties directly (or a Properties or ResourceBundle instance) as a test?  If that works, it would point to an auto-wiring isue with Spring.

**Comment by essiembre** [comment]
Sorry, but I do not understand what you are trying to do.  Could you please elaborate?  

Are you talking about files sent to your committer for deletion?  If so, you can write your own committer and add what you want there.

**Comment by jayjamba** [comment]
You got that right. Thanks writing my own committer did the job.

**Comment by essiembre** [comment]
Great. Thanks for confirming.
