### ISSUE TITLE
Question - splitting up XML files (square peg use-case)

### ISSUE THREAD

**Issue by danizen** [Norconex/collector-filesystem#22]
One thing we often do is crawl a directory full of XML files where each XML file represents multiple documents.   An XPath expression governs how to split the XML file into documents.

Such indexing can be done via a script, but there is some utility for being able to express it all in an XML configuration file, with parameters drawn from properties/vars.   There is further utility in being able to get the status of the indexing in the same way as other indexing (which norconex-jef does provide).

Is this a use case than can be met with the filesystem crawler?   I understand the strength of the filesystem crawler to be unstructured data, such as a heap of PDFs, but I'm hoping it can do this as well.

**Comment by danizen** [comment]
Never mind - I will investigate whether I can attach a Jef monitor to something like a Kettle ETL job. Talend is its own thing.

**Comment by essiembre** [comment]
You can look at using ``DOMSplitter`` if your XMLs are not too big.  If they are quite large, you can create your own ``IDocumentSplitter`` that streams the XMLs instead.  

Not sure it ould fit your status monitoring requirements, but it should address your splitting needs.
