### ISSUE TITLE
Incorrect contentFamily

### ISSUE THREAD

**Issue by jmrichardson** [Norconex/collector-filesystem#23]
Hi, I have noticed that certain files are not being correctly categorized. For example, a word file will be categorized as "other".  Here is the commit xxxx-add.meta for a word document:

```
document.contentFamily = other
collector.lastmodified = 1339515615000
collector.filesize = 48156
type = Client Files
...
```
There are no error produced for the file on ingest in the logs.    We are also seeing video "mp4" files classified as other as well.  This is not happening for all word docs or video files...

Is there a way to enable debugging to see how this file is being parsed as "other".  Thanks for any help.

**Comment by essiembre** [comment]
You can look at the DebugTagger of the Importer module to print the fields extracted/created so far wherever in your Importer handlers config.

If the ``document.contentFamily`` is wrong, it is likely that the content-type was not detected properly.  Can you share what is the value of the ``document.contentType`` field?

In addition, can you share a sample file to help reproduce?
