### ISSUE TITLE
Is there any way to inject/autowire spring beans in norconex specific class

### ISSUE THREAD

**Issue by jayjamba** [Norconex/collector-filesystem#26]
Hi,
I was wondering if I can inject/autowire spring beans in norconex specific class which I overrode for my requirement.
 Lets say I am implementing my own MyTransformer which implements 'IDocumentTransformer', how can I autowire/inject spring beans in it ?

**Comment by essiembre** [comment]
If you are trying to integrate your custom transformer directly into your Spring app, would think you can treat it just like you would with other beans you may have created in your project.   If you want to integrate the FileSystem Collector app itself into a spring app, it may be more challenging.  I would try to focus on wiring [FilesystemCollectorConfig](https://www.norconex.com/collectors/collector-filesystem/latest/apidocs/com/norconex/collector/fs/FilesystemCollectorConfig.html).  Probably simpler to rely on Spring configuration files to wire classes you are not subclassing.

It may be worth asking the Spring community for better guidance as the FileSystem Collector does not use Spring.
