### ISSUE TITLE
If only ACL gets changed of the file, it should get crawled again, but its getting rejected

### ISSUE THREAD

**Issue by jayjamba** [Norconex/collector-filesystem#31]
[1.2.zip](https://github.com/Norconex/collector-filesystem/files/1937586/1.2.zip)

Hi,
I crawled one file, which had acls for 3 users, now lets say if I add one more user in its acl, it should generate an xml when we run for the second time, However the file is getting rejected.

I had to deliberately remove the store to get its updated acls and I have attached both xml files having updated acls.

**Comment by essiembre** [comment]
Why were they rejected? What are the logs saying?  If they are ``REJECTED_UNMODIFIED``, the reason is likely because the checksum being created to evaluate if a file has changed does not take into account the ACL.  

By default, the file system collector creates a checksum from metadata fields before a document is parsed with  [FileMetadataChecksummer](https://www.norconex.com/collectors/collector-filesystem/latest/apidocs/com/norconex/collector/fs/checksum/impl/FileMetadataChecksummer.html) and if another one after the content is parsed using [MD5DocumentChecksummer](https://www.norconex.com/collectors/collector-core/latest/apidocs/com/norconex/collector/core/checksum/impl/MD5DocumentChecksummer.html).  

You can replace the first one with [GenericMetadataChecksummer](https://www.norconex.com/collectors/collector-core/latest/apidocs/com/norconex/collector/core/checksum/impl/GenericMetadataChecksummer.html) if you like and/or configure the second one to consider additional fields when creating a checksum (to include the ACL in your case).

**Comment by jayjamba** [comment]
I used GenericMetadataChecksummer, by default its just concatenating all the metadata starting with these checksum and when I modify the acl its not considering it as changed and says REJECTED_UNMODIFIED.

`<metadataChecksummer 
      class="com.norconex.collector.core.checksum.impl.GenericMetadataChecksummer"
      keep="true" targetField="checksum">
	   <sourceFieldsRegex>collector.acl.*</sourceFieldsRegex>
</metadataChecksummer>`


Checksum of collector.acl.* metadata after the first run:
 <meta name="checksum">collector.acl.smb[0].type=1;collector.acl.smb[0].domainSid=S-1-5-21-3343554865-3455242687-4029084934;collector.acl.smb[0].ace=Allow 26PJXH2\jai.jamba         0x001F01FF Inherited This folder only                  ;collector.acl.smb[1].sid=S-1-5-32-544;collector.acl.smb[0].accountName=jai.jamba;collector.acl.smb[1].accountName=Administrators;collector.acl.smb[2].domainSid=S-1-5;collector.acl.smb[2].accountName=SYSTEM;collector.acl.smb[0].sidAsText=26PJXH2\jai.jamba;collector.acl.smb[2].type=5;collector.acl.smb[2].ace=Allow SYSTEM                    0x001F01FF Inherited This folder only                  ;collector.acl.smb[1].domainSid=S-1-5-32;collector.acl.smb[1].sidAsText=Administrators;collector.acl.smb[2].sid=S-1-5-18;collector.acl.smb[1].type=4;collector.acl.smb[1].typeAsText=Local group;collector.acl.smb[0].domainName=26PJXH2;collector.acl.smb[0].typeAsText=User;collector.acl.smb[1].ace=Allow Administrators            0x001F01FF Inherited This folder only                  ;collector.acl.smb[2].typeAsText=Builtin group;collector.acl.smb[0].sid=S-1-5-21-3343554865-3455242687-4029084934-1003;collector.acl.smb[1].domainName=BUILTIN;collector.acl.smb[2].domainName=NT AUTHORITY;collector.acl.smb[2].sidAsText=SYSTEM;</meta>


Checksum of collector.acl.* metadata THAT SHOULD BE after the second run:
<meta name="checksum">collector.acl.smb[3].ace=Allow SYSTEM                    0x001F01FF Inherited This folder only                  ;collector.acl.smb[3].domainSid=S-1-5;collector.acl.smb[0].type=1;collector.acl.smb[3].sidAsText=SYSTEM;collector.acl.smb[0].domainSid=S-1-5-21-3343554865-3455242687-4029084934;collector.acl.smb[0].ace=Allow 26PJXH2\test              0x001200A9 Direct    This folder only                  ;collector.acl.smb[1].sid=S-1-5-21-3343554865-3455242687-4029084934-1003;collector.acl.smb[0].accountName=test;collector.acl.smb[1].accountName=jai.jamba;collector.acl.smb[2].domainSid=S-1-5-32;collector.acl.smb[2].accountName=Administrators;collector.acl.smb[0].sidAsText=26PJXH2\test;collector.acl.smb[2].type=4;collector.acl.smb[2].ace=Allow Administrators            0x001F01FF Inherited This folder only                  ;collector.acl.smb[1].domainSid=S-1-5-21-3343554865-3455242687-4029084934;collector.acl.smb[3].accountName=SYSTEM;collector.acl.smb[1].sidAsText=26PJXH2\jai.jamba;collector.acl.smb[2].sid=S-1-5-32-544;collector.acl.smb[1].type=1;collector.acl.smb[3].domainName=NT AUTHORITY;collector.acl.smb[1].typeAsText=User;collector.acl.smb[0].domainName=26PJXH2;collector.acl.smb[0].typeAsText=User;collector.acl.smb[1].ace=Allow 26PJXH2\jai.jamba         0x001F01FF Inherited This folder only                  ;collector.acl.smb[2].typeAsText=Local group;collector.acl.smb[0].sid=S-1-5-21-3343554865-3455242687-4029084934-1004;collector.acl.smb[1].domainName=26PJXH2;collector.acl.smb[2].domainName=BUILTIN;collector.acl.smb[2].sidAsText=Administrators;collector.acl.smb[3].sid=S-1-5-18;collector.acl.smb[3].typeAsText=Builtin group;collector.acl.smb[3].type=5;</meta>


I had to explicitly delete store to get the updated acls checksum

**Comment by jayjamba** [comment]
Need to combinely use GenericMetadataChecksummer and MD5DocumentChecksummer to get this thing working. Using either of them will not generate the xml

**Comment by essiembre** [comment]
So it is working for you now?

**Comment by jayjamba** [comment]
yes. You can close it. Also the other one #32 is same.
