### ISSUE TITLE
Change in values of ConstantTagger values is not generating xml in subsequent run.

### ISSUE THREAD

**Issue by jayjamba** [Norconex/collector-filesystem#32]
Hi,
I added constant tagger at Importer level config, those were added as metadata in the resultant xml, which is fine. But now I modified those values, however xml is not getting generated. I think the checksum of the metadata did got changed with those change in values of constant tagger which were included, but it was rejected saying rejected_unmodified.

**Comment by essiembre** [comment]
This looks like a duplicate of #31 (same cause and solution).  Please confirm.
