### ISSUE TITLE
unnecessary extra title & dc:title named metadata are added

### ISSUE THREAD

**Issue by jayjamba** [Norconex/collector-filesystem#35]
Hi,
How can I suppress the title and dc:title added by norconex api from xml. I just want to include these tags which are derived from tika.

Tika derived : 
`<meta name="dc:title">Competitive Landscape Overview for Fyn</meta>`
`<meta name="title">Competitive Landscape Overview for Fyn</meta>`

Norconex added : 
`<meta name="dc:title">/docProps/thumbnail.jpeg</meta>`
`<meta name="title">/docProps/thumbnail.jpeg</meta>`

I have attached the generated xml in which extra title and dc:title are added apart from what Tika derived. I have also attached the sample config xml and the source file which is getting parsed.
[Fyn Competitive Landscape 30-06-2017.pptx](https://github.com/Norconex/collector-filesystem/files/2092801/Fyn.Competitive.Landscape.30-06-2017.pptx)
[configXml&sourceFile.zip](https://github.com/Norconex/collector-filesystem/files/2092810/configXml.sourceFile.zip)

**Comment by jayjamba** [comment]
Hi,
I added KeepOnlyTagger as below:
`<importer>
        <postParseHandlers>
	         <tagger class="com.norconex.importer.handler.tagger.impl.KeepOnlyTagger">
			  <fields>dc:title, title, subject, dc:subject</fields>
		  </tagger>
        </postParseHandlers>
      </importer>`
However the file that is generated now has just these metadata only, **its not that I don't want other metadatas, its just that I want api not to add or derive the same metadata which are derived by tika**.
Also the problem still persists coz it has 2 dc:title and 2 title named metadata. 1 was derived by tika and 1 was derived by norconex api (which seems incorrect).

Tika derived metadata:
`<meta name="dc:title">Competitive Landscape Overview for Fyn</meta>`
`<meta name="title">Competitive Landscape Overview for Fyn</meta>`

Norconex derived metadata:(below metadata seems incorrect, i want to suppress these)
`<meta name="dc:title">/docProps/thumbnail.jpeg</meta>`
`<meta name="title">/docProps/thumbnail.jpeg</meta>`
[add-2018-06-13T11-03-26-457_3.zip](https://github.com/Norconex/collector-filesystem/files/2096728/add-2018-06-13T11-03-26-457_3.zip)

**Comment by essiembre** [comment]
The fields you describe are all extracted by Tika.  Those that are added by the Filesystem Collector start with  ``collector.*`` and those added by the Importer module are starting with ``document.*``.   

If you want to eliminate all those, you can use ``DeleteTagger`` with regular expression.

To avoid duplicates in general, you can have a look at the ``ForceSingleValueTagger`` or ``MergeTagger``.

**Comment by jayjamba** [comment]
Hi,
Well I am using tika's app jar (http://www.apache.org/dyn/closer.cgi/tika/tika-app-1.17.jar) to cross verify the metadata fetched by tika. Its not giving 2 dc:title and title metadata tag for the given source file, it just gives one for each.
`<meta name="dc:title">Competitive Landscape Overview for Fyn</meta>
<meta name="title">Competitive Landscape Overview for Fyn</meta>`

Not sure then how come below 2 are added as metadata
`<meta name="dc:title">/docProps/thumbnail.jpeg</meta>
<meta name="title">/docProps/thumbnail.jpeg</meta>`
It would be great if you can check how come the above 2 metadata are added for attached file.

[Fyn Competitive Landscape 30-06-2017.pptx](https://github.com/Norconex/collector-filesystem/files/2101012/Fyn.Competitive.Landscape.30-06-2017.pptx)

**Comment by essiembre** [comment]
That's because the Norconex Importer extracts embedded documents by default and combines the metadata.  There is an embedded component (e.g., image) with a ``dc:title``.  The view you are using in the Tika app does not show this.  You can see Tika does extract it if you choose ``View -> Recursive JSON`` instead.

If you do not want to parse embedded files, you can prevent it by adding the following in your importer config section:

```xml
  <documentParserFactory>

      <embedded>
          <noExtractContainerContentTypes>
              application/vnd\.openxmlformats-officedocument.*
          </noExtractContainerContentTypes>
      </embedded>
      
  </documentParserFactory>
```

Have a look at the [GenericDocumentParserFactory](https://www.norconex.com/collectors/importer/latest/apidocs/com/norconex/importer/parser/GenericDocumentParserFactory.html) for more parsing options (like splitting embedded files instead).

**Comment by essiembre** [comment]
``noExtractEmbeddedContentTypes`` prevents extracting embedded files of matching content types.  As an example, you would use it if you do not mind extracting JPG files, but not if they are embedded in other files (the approach you did).   Like:

```
- [YES] picture.jpg
- [YES] word.doc
     - [YES] embedded-spreadsheet.xls
     -  [NO] embedded-picture.jpg
     - [YES] embedded-whatever.txt
- [YES] archive.zip
     - [YES] embedded-spreadsheet.xls
     -  [NO] embedded-picture.jpg
     - [YES] embedded-whatever.txt
```

``noExtractContainerContentTypes`` prevents extracting ANY embedded files found in parent files of matching content types. For example, your may want not to extract embedded files just for Word docs:

```
- [YES] picture.jpg
- [YES] word.doc
     - [NO] embedded-spreadsheet.xls
     - [NO] embedded-picture.jpg
     - [NO] embedded-whatever.txt
- [YES] archive.zip
     - [YES] embedded-spreadsheet.xls
     - [YES] embedded-picture.jpg
     - [YES] embedded-whatever.txt
```

Regular expression let's you specify more than one string to match.  For your example, it could look like this (not tested):
```xml
<noExtractContainerContentTypes>
    (application/vnd\.openxmlformats-officedocument.*|application/pdf)
</noExtractContainerContentTypes>
```
