### ISSUE TITLE
Query regarding ORPHAN STRATEGY.

### ISSUE THREAD

**Issue by jayjamba** [Norconex/collector-filesystem#43]
Hi,
I have one query regarding ORPHAN STRATEGY which has value DELETE, ORPHAN AND PROCESS.
By default its PROCESS, which will process older scanning paths even if we modify from one scanning path to another path.
In case of DELETE, it will generate delete xml of the older scanning paths if we modify from one scanning path to another path.
And in case of IGNORE, it will simply ignore the older scanning path if we modify from one scanning path to another path.

My question is in case of IGNORE it is not even generating delete xmls if we don't modify the scanning path and delete some files from that path. Is it like we need to keep our strategy as DELETE if we want deleted xmls?

I want something like combination of all three strategies :), It should completely ignore (dont process OR generate delete xmls) the older scanning path if modified to newer path. And it should generate delete xmls only in case if the path encountered is same and we actually deleted some file from that specific path which it is currently scanning.

**Comment by essiembre** [comment]
That is correct.  IGNORE is when you don't want to do anything with "orphans".    DELETE will not bother to verify if they still exist or not. It assumes you no longer want them and sends a removal request to your Committer.
