### ISSUE TITLE
Getting statistics through norconex api

### ISSUE THREAD

**Issue by jayjamba** [Norconex/collector-filesystem#44]
Hi,

Is there any way in api, where I can get the statistics of the total files in process, crawled etc. the one that are printed in logs.

**Comment by essiembre** [comment]
Yes, you can implement your own [ICrawlerEventListener](http://www.norconex.com/collectors/collector-core/latest/apidocs/com/norconex/collector/core/crawler/event/ICrawlerEventListener.html) and you will be notified on every crawling events (have a look [here](http://www.norconex.com/collectors/collector-core/latest/apidocs/com/norconex/collector/core/crawler/event/CrawlerEvent.html) for a list of events).
