### ISSUE TITLE
Is there any way I can get the total count of the files to be processed.

### ISSUE THREAD

**Issue by jayjamba** [Norconex/collector-filesystem#46]
Hi,
Is there any way in norconex to get the total count of files to be processed, which includes all the files residing in folder/subfolder etc. ?

**Comment by essiembre** [comment]
A the end of the generated log file is a summary and it tells you how many were processed.  "Processed" does not necessarily mean sent to your Committer though.  Some may be rejected.  

It really depends what number you are looking for.  For instance, if you are interested in only those that we sent to your Committer in a crawl session, you have few options, like:

- If on linux, you can use grep and wc on the log file.  E.g.: ``grep "DOCUMENT_COMMITTED_ADD" mylog.log | wc -l``.
- You could add a date constant to your crawl and then filter all records more recent than that date in your target repository (see [CurrentDateTagger](https://www.norconex.com/collectors/importer/latest/apidocs/com/norconex/importer/handler/tagger/impl/CurrentDateTagger.html)).
- You can create your own crawler event listener.  Have a look at [ICrawlerEventListener](https://www.norconex.com/collectors/collector-core/latest/apidocs/com/norconex/collector/core/crawler/event/ICrawlerEventListener.html), which can be added to your crawler config with: 

```xml
            <crawlerListeners>
                <listener class="YourOwnListner"/>
            </crawlerListeners>
```

That even listener will be notified of all crawl actions.  Up to you to count the ones of interest to you and store that count wherever you see fit.

Can one of these suggestions work for you?

**Comment by jayjamba** [comment]
I created my own ICrawlerEventListener, which did the job. Thanks !
