### ISSUE TITLE
Issue with duplication while Crawling

### ISSUE THREAD

**Issue by Ashish1109** [Norconex/collector-filesystem#52]
Hi Team,

I'm trying to crawl a website and I face duplication of URL's while crawling. The issue is that the URL is appended with nested responses(methods/..//methods/..//...). Is there any way I can avoid this in my XML?

I have attached a screenshot for reference

![image](https://user-images.githubusercontent.com/18701917/82341879-97513280-99b6-11ea-8aba-0fdffe638b6c.png)

**Comment by essiembre** [comment]
Are you really using the Filesystem Collector, or the HTTP Collector? 

If the latter, the HTTP Collector has a ``GenericURLNormalizer`` class that will resolve those types of URLs with the normalization rule ``removeDotSegments``.   Please use the proper channel if you have more questions on this: https://github.com/Norconex/collector-http/issues

If you really meant the Filesystem Collector, what type of filesystem are you crawling?

**Comment by Ashish1109** [comment]
@essiembre Thank you so much that worked like a magic. I was not able to find the documentation so I had to create an issue. Sorry!!

Is there support for general types of questions like these?

Thank You!!

**Comment by essiembre** [comment]
@Ashish1109 , thanks for the update.  Github is the right community forum for questions so keep asking.  My comment was simply about you picking the wrong one (Filesystem Collector vs HTTP Collector).   

Did you mean professional support?  See here for options:  https://norconex.com/collectors/collector-http/support
