### ISSUE TITLE
Release 2.9 sources are not on GitHub

### ISSUE THREAD

**Issue by radomirml** [Norconex/collector-filesystem#53]
Release 2.9 was released in 2019 and is offered for download on the website but the sources are not in GitHub. I need to make some customizations for the project I'm working on and would be once to extend the latest release. :)
Thanks.

**Comment by radomirml** [comment]
I've found 2.9 source in the devlop branch.

**Comment by essiembre** [comment]
Hello Radomir!  Thanks for reporting this, I have updated master with the 2.9.0 code.
