### ISSUE TITLE
Cannot encrypt credentials per FAQ

### ISSUE THREAD

**Issue by RussellGrew** [Norconex/collector-filesystem#55]
Following https://norconex.com/collectors/collector-http/faq#toc10

The first step is good

```
java -cp norconex-commons-lang-1.15.1.jar com.norconex.commons.lang.encrypt.EncryptionUtil
```
yields
```
<appName> encrypt|decrypt -k|-f|-e|-p key text

Where:
  encrypt  encrypt the text with the given key
  decrypt  decrypt the text with the given key
  -k       key is the encryption key
  -f       key is the file containing the encryption key
  -e       key is the environment variable holding the encryption key
  -p       key is the system property holding the encryption key
  key      the encryption key (or file, or env. variable, etc.)
  text     text to encrypt or decrypt
```
but
```
java -cp norconex-commons-lang-1.15.1.jar com.norconex.commons.lang.encrypt.EncryptionUtil encrypt -f "../../key.txt" "password123"
```
yields
```
Exception in thread "main" java.lang.NoClassDefFoundError: javax/xml/bind/DatatypeConverter
        at com.norconex.commons.lang.encrypt.EncryptionUtil.encrypt(EncryptionUtil.java:185)
        at com.norconex.commons.lang.encrypt.EncryptionUtil.main(EncryptionUtil.java:101)
Caused by: java.lang.ClassNotFoundException: javax.xml.bind.DatatypeConverter
        at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:581)
        at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:178)
        at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:521)
        ... 2 more
```

where key.txt contains a 32 character string generated from some website.

I also tried this against the commons-lang download. No good. Advice invited.

Thanks.

**Comment by essiembre** [comment]
Are you using a more recent JRE such as version 9 or higher?  If so, the missing class is not part of a java "module" that does not ship with java anymore in those versions.  For more explanations and to add the missing module, I recommend you check [this](https://stackoverflow.com/questions/43574426/how-to-resolve-java-lang-noclassdeffounderror-javax-xml-bind-jaxbexception-in-j#43574427).

Another option is to use Java 8.

**Comment by RussellGrew** [comment]
Thanks @essiembre this turned out to be a non issue together with the mapped drive per https://github.com/Norconex/collector-filesystem/issues/54 whereby the `optionsProvider` section of the config is no longer required.

For reference I am running OpenJDK 11.
