### ISSUE TITLE
Error with Solr Committer

### ISSUE THREAD

**Issue by julied20** [Norconex/collector-filesystem#6]
Hi,

I'm trying to run the example from the filesystem by replacing the FileSystemCommitter with the SolrCommitter.
So the config file looks like that:

`<?xml version="1.0" encoding="UTF-8"?>
  <fscollector id="Text Files">
  <logsDir>${workdir}/logs</logsDir>
  <progressDir>${workdir}/progress</progressDir>

  <crawlers>
    <crawler id="Sample Crawler">

      <workDir>${workdir}</workDir>

      <startPaths>
        <path>${path}</path>
      </startPaths>
      
      <numThreads>2</numThreads>

      <keepDownloads>true</keepDownloads>      
      
      <committer class="com.norconex.committer.solr.SolrCommitter">
	    <solrURL>http://localhost:8983/solr/file/</solrURL>				
	    <commitDisabled>false</commitDisabled>
       </committer>
    </crawler>
  </crawlers>
</fscollector>`

Everything is going fine until it comes to commit the files into my Solr instance. There I have the following error:
[SolrError.txt](https://github.com/Norconex/collector-filesystem/files/390074/SolrError.txt)

I assumed that to commit the files into Solr, it was working the same way as with the http collector, am I missing something?

Thank you in advance

**Comment by essiembre** [comment]
I have made a quick search and ``java.lang.VerifyError`` typically occurs when there is code compiled against a different library than you are using at runtime.   

One way maybe this can happen for you is if you have duplicate JARs of different versions.  Can you look into your ``lib`` folder and ensure you do not have the same library twice, with different version?

Did you start from a fresh install of the filesystem committer?

**Comment by julied20** [comment]
Yeah... I've just looked and I found that I had two differents versions of the http-client JAR..
Thank you for your quick answer on this!
