### ISSUE TITLE
REJECTED_NOTFOUND for files with Umlaute like ä

### ISSUE THREAD

**Issue by schudoku** [Norconex/collector-filesystem#65]
Files with Umlaute do not get fetched:

> INFO  [CrawlerEventManager] Crawler:         REJECTED_NOTFOUND: file:///C:/dev/test-with-├ñ.txt

original file name: test-with-ä.txt

**Comment by Czaniolo** [comment]
Hi, Pascal

I have the same problem with special characters in the portugueses language...

**Comment by essiembre** [comment]
I was able to reproduce it (on Windows). Marking as a bug.

**Comment by essiembre** [comment]
A new 2.9.2-SNAPSHOT release was made with a fix.  Please give it a try and confirm.

**Comment by Czaniolo** [comment]
Hi, Pascal

It worked perfectly for me. It solved the Portuguese accentuation problem.

Thanks for the prompt reply.

Best Regards!
