### ISSUE TITLE
ExtensionReferenceFilter 0nMatch="include" not working

### ISSUE THREAD

**Issue by Czaniolo** [Norconex/collector-filesystem#67]
Hi,

Thanks for sharing this crawler.

I cannot filter out files with specific file types (.doc or .docx, for example) in directories and subdirectories. It only works if there are already files in the examples-output directory. The first time the crawler is run it does not return any files.
```
<crawlerDefaults>
  <referenceFilters>
    <filter class="com.norconex.collector.core.filter.impl.ExtensionReferenceFilter" onMatch="include">
      doc,docx
    </filter>
  </referenceFilters>
</crawlerDefaults>
```
I have tried using it with RegexReferenceFilter, but it doesn't work either (as suggested in #56):
```
<crawlerDefaults>
  <referenceFilters>
    <filter class="com.norconex.collector.core.filter.impl.RegexReferenceFilter" onMatch="include">
      [A-Za-z0-9\\:]{1,}\.(docx|doc|pptx)$ <!-- or $path\([^\.]+|.*\.(docx|doc))$ -->
    </filter>
  </referenceFilters>
</crawlerDefaults>
```
Both of the above regex work correctly on regex101...

The interesting thing is that ExtensionReferenceFilter, onMatch="exclude" works perfectly on first run.

I hope you can help me.

Thanks!

**Comment by essiembre** [comment]
Ticket #56 also mentions using metadata filters instead.  The following should work for you:

```xml
      <metadataFilters>
        <filter class="com.norconex.collector.core.filter.impl.ExtensionReferenceFilter" onMatch="include">
          doc,docx
        </filter>
      </metadataFilters>
```

Please confirm.

**Comment by Czaniolo** [comment]
Hi, Pascal

It worked perfectly!

Thank you!
