### ISSUE TITLE
config file 

### ISSUE THREAD

**Issue by angelo337** [Norconex/collector-filesystem#7]
hi there
 I am working with your product on a personal project and trying different component's, and I am now trying to configure your Filesystem collector however I'm wondering how should I feed the information about the starting path on the config File; should I use Windows file format or should I uuse Linux File format? like this:

Windows local folder:

> c:\path\to\folder

Windows share folder:

> \ \\share folder\folder

or 
Linux local folder:

> /path/to/folder

Linux share folder:

> smb://path/to/folder

which one of this is right one?, please, 
or either entrances acceptable in the config file?

thanks

**Comment by essiembre** [comment]
On windows you define the path as you normally would on windows.  Same for Linux: you do not have to do anything special when referencing the local file-system.  For other types of paths (like SMB shares), refer to this page for all supported formats: https://commons.apache.org/proper/commons-vfs/filesystems.html

Does that answer?

**Comment by angelo337** [comment]
thanks a lot for your answer, I undestand and figure it out.
