### ISSUE TITLE
Crawling on non mapped locations

### ISSUE THREAD

**Issue by Czaniolo** [Norconex/collector-filesystem#70]
Hi, Pascal

I am working on a small project (for study purpose only) to identify personal data in files, on a LAN network, using File System Crawler to fetch the contents of the files and Microsoft Presidio to identify the PII in those files.

For this, I am working with Windows 10 on my machine and a VM with Windows 7.

On my local machine or if the folder in VM is shared, I can easily find the files (pathwin7 = //WIN7\pasta01). So, up to this point, everything is working very well and I am managing to identify all the PII.

However, if the files are in a non-shared folder (I have a test folder in c:\Users\zaniolo\Desktop\pasta02 - which also contains PII that needs to be identified), I cannot access it and I think this is a common situation, on a real network.

I have tried using this (with jcifs-1.3.17.jar in my lib folder):
```
  <crawlers>
    <crawler id=${ID}>
      <startPaths>
        <path>${pathwin7}</path>
      </startPaths>
      <numThreads>2</numThreads>
      <keepDownloads>false</keepDownloads>

      <optionsProvider class="com.norconex.collector.fs.option.impl.GenericFilesystemOptionsProvider">
        <authDomain>${domain}</authDomain>
        <authUsername>${user}</authUsername>
        <authPassword>${password}</authPassword>
      </optionsProvider>

      <importer>
```
with a configuration file like this:
```
pathwin7 = smb://WIN7\c:\Users\zaniolo\Desktop

domain = WIN7
user = zaniolo
password = 041620
workdir = ./examples-output
```
However, it gives the error:
```
INFO  [CrawlerEventManager] Windows7:           CRAWLER_STARTED
INFO  [AbstractCrawler] Windows7: Crawling references...
INFO  [CrawlerEventManager] Windows7:            REJECTED_ERROR: smb://WIN7\c:\Users\zaniolo\Desktop (com.norconex.collector.core.CollectorException: Cannot resolve: smb://WIN7\c:\Users\zaniolo\Desktop)
INFO  [AbstractCrawler] Windows7: Could not process document: smb://WIN7\c:\Users\zaniolo\Desktop (Cannot resolve: smb://WIN7\c:\Users\zaniolo\Desktop)
INFO  [CrawlerEventManager] Windows7: DOCUMENT_COMMITTED_REMOVE: smb://WIN7\c:\Users\zaniolo\Desktop
INFO  [AbstractCrawler] Windows7: Reprocessing any cached/orphan references...
INFO  [AbstractCrawler] Windows7: Crawler finishing: committing documents.
INFO  [AbstractCrawler] Windows7: 1 reference(s) processed.
INFO  [CrawlerEventManager] Windows7:          CRAWLER_FINISHED
```
I have tried several other settings but I don't know if I'm doing something wrong or if it's really not possible to access non-shared locations....

Thank you

**Comment by Czaniolo** [comment]
Just a correction:

from pathwin7 = //WIN7\pasta01 to pathwin7 = smb://WIN7/pasta01

**Comment by ohtwadi** [comment]
I am not sure what non-shared folders mean here. Can you access the folder inside the VM from the host machine via File Explorer?

**Comment by Czaniolo** [comment]
Hi,

No. I have access only to pasta01, which was shared within WIN7...

**Comment by essiembre** [comment]
Can you mount the path to a windows drive letter?  You will then crawl as if it was a local filesystem.

**Comment by Czaniolo** [comment]
Hi, Pascal

Sorry for the delay. I was testing on a real network and it took me a while to get access to this network.

As this project is premised on small business networks (1 or 2 servers and up to 50 machines, maximum) it is possible to mount the path of each machine individually and share only with the system administrator. That way I can scan any folder in any location, using the administrator's credentials. It's not the ideal solution, because it would be necessary to involve the system administrator, but it works.

Thank you!
